### ISSUE TITLE
Conceal's ctermfg is being overwritten

### ISSUE THREAD

**Issue by hrai** [dodie/vim-disapprove-deep-indentation#13]
I'm using this plugin in conjunction with IndentLine and the colour that I've giving for line indentation is being overwritten by this.

https://github.com/dodie/vim-disapprove-deep-indentation/blob/c53ef5631cdf3e93935574f67aa07fa269766cc1/plugin/vim-disapprove-deep-indentation.vim#L54

Is it possible to remove this line altogether as `ಠ_ಠ` is good enough to visually tell the users of their deep indentation.

**Comment by hrai** [comment]
I was using one of the plugins which was overwriting the ctermfg value.

When I opened vim, I executed `:verbose highlight Conceal` and it gave me the following which helped me pin point the desired script.

![image](https://user-images.githubusercontent.com/4055444/59660251-6804d500-91eb-11e9-9b91-7ba4e3f28465.png)

**Comment by dodie** [comment]
Hi @hrai!

Thank you for the suggestion! Indeed, when this plugin is used in combination with other plugins where the goal of conceal is not to make something more apparent (e.g. the indentation lines), this plugin does not play nicely.

To be honest, I tried to remove the suggested line, and I like the current version better because many schemes do not define conceal colors, in which case the eye of disapproval looks a bit weird:

![image](https://user-images.githubusercontent.com/1114220/59716225-e70f0300-9215-11e9-972f-783a35acd02a.png)

So instead of removing it completely, I'm thinking about some middle ground solution, such as:
- Somehow define a unique conceal color, just for the eye. (Sadly, this seems impossible. :disappointed:)
- Automatically detect when other plugins use conceal feature, and in this case, back off.
- Provide a configuration option to opt-out of setting the conceal color.

Note: I found some similar issues, which might provide inspiration:
- https://github.com/pangloss/vim-javascript/issues/151
- https://github.com/junegunn/seoul256.vim/issues/11

Cheers,
David

**Comment by hrai** [comment]
Hi David,

Perhaps the 3rd solution is the best of the lot.

- Provide a configuration option to opt-out of setting the conceal color.

The conceal colours can be just as they currently are by default and can be customised with the flag as needed.

Thoughts?

H.

**Comment by dodie** [comment]
I came to the same conclusion as it does not break backward compatibility and simple to implement. I created a PR with this functionality. By default, it works the same way as it does now, but if you specify `let g:LookOfDisapprovalNoStyle=1`, it will disable the styling. Could you please give a glimpse?
