### ISSUE TITLE
Doesn't seem to work in CMakeLists.txt files

### ISSUE THREAD

**Issue by jorgehatccrma** [dodie/vim-disapprove-deep-indentation#2]
Great simple idea! 

That said, I'm having issues getting to work for `cmake` (`CMakeLists.txt`) files. I have the following config in my `.vimrc`:

```
...
let g:LookOfDisapprovalTabTreshold=5
let g:LookOfDisapprovalSpaceTreshold=(&tabstop*5)
...
autocmd FileType cmake setlocal sw=4 ts=4 sts=4 expandtab
...
```

which I'm pretty sure is working (I get the right indentation when I enter, for example, `gg=G`).

But I get the following output with this plugin:

```
project(mylib-fat)

set_component_info(${THIS_COMPONENT_NAME} mylib-devel "Development package")

set(PUBLIC_HEADER_FILES
ಠ_ಠ ${CMAKE_BINARY_DIR}/mylib/lib/include/mylib.h
ಠ_ಠ )

add_library(${PROJECT_NAME} STATIC
ಠ_ಠ $<TARGET_OBJECTS:mylib-obj>
ಠ_ಠ $<TARGET_OBJECTS:mymath-obj>
ಠ_ಠ ${PUBLIC_HEADER}
ಠ_ಠ )

set_target_properties(${PROJECT_NAME} PROPERTIES
ಠ_ಠ FRAMEWORK TRUE
ಠ_ಠ FRAMEWORK_VERSION A
ಠ_ಠ MACOSX_FRAMEWORK_IDENTIFIER com.me.me
ಠ_ಠ VERSION ${MYLIB_VERSION}
ಠ_ಠ PUBLIC_HEADER "${PUBLIC_HEADER_FILES}"
ಠ_ಠ OUTPUT_NAME "mylib"
ಠ_ಠ )

install(TARGETS ${PROJECT_NAME}
ಠ_ಠ ARCHIVE DESTINATION lib/static COMPONENT  ${THIS_COMPONENT_NAME}
ಠ_ಠ FRAMEWORK DESTINATION framework COMPONENT ${THIS_COMPONENT_NAME}
ಠ_ಠ PUBLIC_HEADER DESTINATION include COMPONENT ${THIS_COMPONENT_NAME}
ಠ_ಠ )
```

Any idea why?

**Comment by theneva** [comment]
![image](https://cloud.githubusercontent.com/assets/1404650/23656509/50e245a2-033a-11e7-977c-1eedb95863aa.png)

I'm seeing the same thing in an SQL file fwiw, tabstop is 2.

Edit: I also can't turn them off by setting the values to 0

Edit 2: I'm on macOS Sierra using VIM 7.4.1910 from Homebrew

**Comment by myoung34** [comment]
Ditto on ruby:

```
require 'vagrant'
require 'filesize'
require 'ovirtsdk4'

module VagrantPlugins
ಠ_module OVirtProvider
ಠ_ಠ class Config < Vagrant.plugin('2', :config)

ಠ_ಠ   attr_accessor :url
```

vimrc:

```
NeoBundle 'dodie/vim-disapprove-deep-indentation'
let g:LookOfDisapprovalTabTreshold=0
let g:LookOfDisapprovalSpaceTreshold=(&tabstop*5)
```

**Comment by dodie** [comment]
It seems that the problem is caused by conflicting syntax rules.
I can reproduce the issue with the default SQL syntax rules on Vim 7.4,
but if I use [these](http://www.vim.org/scripts/script.php?script_id=3702) SQL syntax rules, it works normally.

I'll look into it, but for now I don't know exactly what rules can cause this strange behavior.

**Comment by myoung34** [comment]
`ಠ_ಠ `

**Comment by dodie** [comment]
The problem is caused by existing syntax rules that use ```contains=ALL``` or ```contains=ALLBUT```.
The ```ಠ_ಠ``` shouldn't be applied, except for deeply indented lines, but these rules sabotage this goal.

In the case of SQL I've found this line in the default ```sql.vim```:
```
syn region sqlFold start='^\s*\zs\c\(Create\|Update\|Alter\|Select\|Insert\)' end=';$\|^$' transparent fold contains=ALL
```

Simply changing the line to the following (or redefining in the plugin) solves the problem:
```
syn region sqlFold start='^\s*\zs\c\(Create\|Update\|Alter\|Select\|Insert\)' end=';$\|^$' transparent fold contains=ALLBUT,LookOfDisapprovalLeftEye,LookOfDisapprovalRightEye,LookOfDisapprovalMouth,LookOfDisapprovalPadding
```

Unfortunately, I couldn't reproduce the issue with my Ruby or the cmake syntax files, could you confirm that your versions have rules with the ```contains=ALL``` or ```contains=ALLBUT``` attribute?


I've fixed the issue that in this case, the plugin can't be disabled, so in the future setting the ```g:LookOfDisapprovalTabTreshold``` and ```g:LookOfDisapprovalSpaceTreshold``` variables to zero will remove the look of disapproval in any case. At least if somebody encounters the problem, the plugin can be disabled for that given syntax.


I am planning on extending the docs to draw attention to this issue and provide a copy-pasteable solution to disable the plugin for specific file types. 

If there is a way to detect rules reliably, the plugin could be extended to contain "fixes" for popular syntax files too.

**Comment by theneva** [comment]
Good job figuring that one out! Now I can activate the plugin again :D

**Comment by dodie** [comment]
The fix for the default ruby syntax:
```
syn cluster rubyNotTop add=LookOfDisapprovalLeftEye,LookOfDisapprovalRightEye,LookOfDisapprovalMouth,LookOfDisapprovalPadding
```

**Comment by dodie** [comment]
I've extended the docs with the description of the problem and added fixes for the default SQL and Ruby syntaxes. Unfortunately, I could not reproduce the problem with cmake. I checked the default and [some](https://github.com/nickhutchinson/vim-cmake-syntax) [other](http://www.vim.org/scripts/script.php?script_id=600) rulesets, but they worked correctly with the plugin. 

If it's still not working correctly or you encounter the problem with any other file type, please open an issue for it, just make sure to link the applied syntax file. I'll do my best to put a fix for it to the plugin.

**Comment by dodie** [comment]
While working on another problem I could reproduce and fix the issue with the CMake syntax as well.
