### ISSUE TITLE
Not work in *.rb (w/ or w/o EditorConfig)

### ISSUE THREAD

**Issue by zx1986** [dodie/vim-disapprove-deep-indentation#5]
But it works fine in PHP, Python. 
Have no clues :-(

```
  1 class Api::V1::MembersController < Api::ApiController
  2 ಠ_acts_as_token_authentication_handler_for User, except: [:login, :create]
  3
  4 ಠ_def login
  5 ಠ_ಠ member = User.find_by_sid(params[:sid])
  6 ಠ_ಠ if member.present? and member.valid_password?(params[:password])
  7 ಠ_ಠ   sign_in member
  8 ಠ_ಠ   loanpost = member.active_loanpost
  9 ಠ_ಠ   if loanpost
 10 ಠ_ಠ     loanpost_id = loanpost.id
 11 ಠ_ಠ     loanpost_step = loanpost.step
 12 ಠ_ಠ   else
 13 ಠ_ಠ     loanpost_id = ''
 14 ಠ_ಠ     loanpost_step = 'step0'
```

**Comment by dodie** [comment]
The problem is caused by existing syntax rules that use contains=ALL or contains=ALLBUT.
See issue #2 for details.

The issue with ruby syntax highlighting can probably be solved by adding the following line to your vimrc:

```
syn cluster rubyNotTop add=LookOfDisapprovalLeftEye,LookOfDisapprovalRightEye,LookOfDisapprovalMouth,LookOfDisapprovalPadding
```

Currently, I am looking for a reliable way to add this fix to the plugin. Could you verify that the fix works for you?

Thanks!

**Comment by zx1986** [comment]
I got no `contains=*` setting, I run vim with spf13 config repo.
And I had try the config `syn cluster`, but it didn't work :-( 

But I thought I should close this issue and join into issue #2.
